### ISSUE TITLE
タイトルの_について

### ISSUE THREAD

**Issue by kariya-mitsuru** [cpprefjp/site_generator#10]
タイトルに _ が入っている場合はどのように書けばよいのでしょうか？
[事前定義識別子\_\_func\_\_](http://cpprefjp.github.io/lang/cpp11/func.html) のタイトルとかサイドバーとかが悲しい事になってるので直したいのですが、どのように書けばいいのか分かりません。

**Comment by faithandbrave** [comment]
@melpon に以前確認したところ、タイトル(見出し1)はなにも修飾しないで記述するのが方針だそうなので、site_generator側でタイトルのエスケープを処理する必要がありますね。

**Comment by melpon** [comment]
方針としては３つほど考えられます。

1. タイトルはMarkdown→HTMLへの変換を行わないようにする
2. タイトルを取得する処理でエスケープを認識してテキスト化する
3. 気にしない

まぁ3.は論外とすれば、1.,2.はどちらもsite_generatorを弄ることになります。
実装としては2.の方が楽で、多分[この辺](https://github.com/cpprefjp/site_generator/blob/master/run.py#L131)を改造するだけで済むかなと思います。
 1.の方は、[この辺](https://github.com/cpprefjp/site_generator/blob/master/run.py#L84)で読んでるデータをタイトルとそれ以外に分けて、後でHTMLとして結合する必要があって、ちょっと手間が掛かりますね。

**Comment by kariya-mitsuru** [comment]
書くときはちょっと面倒ですが、Markdown 形式でもちゃんと見える 2 の方がいいかなぁ、と思うのですが、いかがでしょう？

**Comment by melpon** [comment]
良いと思います。楽ですし。

**Comment by faithandbrave** [comment]
取り組む人が決まったら、担当を設定してくださいね。

**Comment by melpon** [comment]
@kariya-mitsuru さんのPRをマージしたので、明日には直ってるはずです。
直ってたらcloseしましょう。

**Comment by melpon** [comment]
直ってたのでcloseします。
<img width="228" alt="2016-04-22 14 04 06" src="https://cloud.githubusercontent.com/assets/816539/14732211/527e55e2-0893-11e6-9da1-235fbd609583.png">
