### ISSUE TITLE
cpprefjp: パンくずリストのサイト名表記が冗長

### ISSUE THREAD

**Issue by saki7** [cpprefjp/site_generator#18]
glyphiconを既に使ってるので、ここもアイコンにするとすっきりします。

```css
<i class="glyphicon glyphicon-home"></i>
```

---

![image](https://user-images.githubusercontent.com/1901813/29577006-d6224fc0-87a4-11e7-843a-8781184937ae.png)

![image](https://user-images.githubusercontent.com/1901813/29577149-6223a0be-87a5-11e7-85e4-f7df490d7522.png)

**Comment by saki7** [comment]
https://github.com/cpprefjp/site_generator/blob/36a6bbb6bfff86c3d5f6fb23223107650ee499ff/cpprefjp/templates/content.html#L48

ここのループで、1個目の要素の時だけ特別扱いすれば実装できると思います（python分からないっす……すいません）

**Comment by melpon** [comment]
直しました（たぶん）。1時間後ぐらいに反映されると思います。
@saki7 大丈夫そうなら close しておいて貰えると。

（これ書いてて思い出したのですが、site_generator で生成したサイト、HTML5 の validator に掛けると大量にエラーが出るの何とかしたいですね

**Comment by saki7** [comment]
@melpon あざっす！ `loop` とかいうオブジェクトあるんですね。テンプレートエンジンっぽい。

HTML5のバリデーションに関しては、ヤバそうなやつだけ取り急ぎIssue立てます。
