### ISSUE TITLE
boostjp に cpprefjp のアイコン類が表示される

### ISSUE THREAD

**Issue by saki7** [cpprefjp/site_generator#21]
https://boostjp.github.io/

site_generator に cpprefjp のアイコン回りの変更を入れた時に、 コードベースを共有してる boostjp の方にも間違って反映されてしまったのだと思います……

**Comment by usagi** [comment]
さしあたり一応区別可能なように色違い版でも用意してboostjpにも"無いよりは"という事でアイコン設定してしまうとかどうだろう。

**Comment by faithandbrave** [comment]
あー。boostjpのbase.htmlがcpprefjpへのシンボリックリンクになってますね。

**Comment by faithandbrave** [comment]
修正しました。日時更新を待ちましょう。

**Comment by faithandbrave** [comment]
@melpon 
もしかしたら、boostjpのGitHub Pagesリポジトリから、`static/favicon`と`static/original-icons`ディレクトリを手動で消してもらわないといけないかもしれません。site_generatorの実行時に、まっさらにしてたら大丈夫ですが。

**Comment by saki7** [comment]
対応ありがとうございます……

**Comment by faithandbrave** [comment]
faviconとかのディレクトリは消えてくれましたが、base.htmlにまだfaviconの設定が残っていました。また後日の更新待ちですね。

**Comment by saki7** [comment]
直ってました。ありがとうございました！
