### ISSUE TITLE
site_generator 自身を push した時に cpprefjp/boostjp を再生成したい

### ISSUE THREAD

**Issue by saki7** [cpprefjp/site_generator#26]
93fb8ca120c5b882d8f080123f77c6953c531658 を反映させたくて push したのですが更新されていないようだったので、暫定措置の暫定措置として https://github.com/cpprefjp/site/commit/1b800d3bc3ccb73ddc3e5b96956f16d2d2a5ede9 のような `--allow-empty` をしてみたのですが依然として反映されず……

@melpon おそらく site_generator 自身にwebhookって設定されてない……のですかね？

**Comment by melpon** [comment]
あー、設定してないですね。今のところ webhook あるのは site と crsearch だけです。
静的ファイルの更新だけでいいなら時間は掛からないので、そういう更新をするようにwebhook入れておきます。

\# site_generator を書き換えて push するのは、今までは吐き出す html を変えたい場合が多くて、その場合は全ての md ファイルを変換し直す必要があり、それが1時間ぐらい掛かるからやっていませんでした。（デイリーの全更新に任せてる）

**Comment by saki7** [comment]
あーなるほど。 site_generator 自身を更新した時に全ての md を変換し直す必要があるというのは、おそらく原理的にそうならざるをえないですね。

ただ、 93fb8ca120c5b882d8f080123f77c6953c531658 は本来はアセットレベルで分離しないと根本的解決にならない種の変更なので、「静的ファイルだけ更新する」のはとりあえず wontfix でいいと思います（フロントエンドをリニューアルする時にまとめて直した方がいいと思います）。

一方で、 site_generator 自身の更新（つまり全てのmdを再変換する必要性がある変更） も色々と入れたいので（e.g. メタタグの整理とか）、 site_generator 自身のディープな webhook は欲しいです。

boostjpとcpprefjpの規模感は把握しているので再変換に多少時間がかかるのは分かるのですが、全ての再変換に１時間かかるのは流石にヤバいと思うので、ベンチマークを取って Python スクリプト自体を直すパッチを書こうかと考えてます（どの辺がヤバいとかあれば教えて頂ければ）。

**Comment by melpon** [comment]
一番時間が掛かっているのは [minify 処理](https://github.com/cpprefjp/site_generator/blob/93fb8ca120c5b882d8f080123f77c6953c531658/run.py#L112) です。minify しないだけで掛かる時間が4分の1ぐらいになります。
ただ、そもそも生成された HTML はサイトマップ（左側の HTML）が大半を占めているので、 @saki7 さんならサイトマップの情報を外部に置いといて、それを動的に読んでロードするとかできそうな気もしてます。そうするとほとんど時間が掛からないんじゃないかなと思います。

**Comment by saki7** [comment]
minify について→ #27

---

サイドバーを動的に取る件については賛成です。サイトマップがあるのでHTMLからは削っても問題ないでしょう。

※強いて言うなら site_generator の生成完了時に Google Search Console （旧 Google ウェブマスターツール） のAPIに更新通知するリクエストを１個追加した方が良いとは思いますが、認証周りが大変そう

※既に googlebot は [デフォルトでサイトマップを読みに行っているはず](https://cpprefjp.github.io/robots.txt) なので、Google Search Console へはデータそのものではなくメタデータの再フェッチの要請をするだけでいいはず

サイドバー→ #28 

---

割と脱線しましたが、この Issue としては push 時に site_generator の webhook が走ってもらえれば今の段階では1時間とかかかっても良いので、上記２つのIssueはとりあえず後回しで考えて頂ければ。

**Comment by melpon** [comment]
webhook を設定しておきました。
site_generator の webhook が走っている間は他の webhook は動かないので、例えば site_generator を更新中に site を更新した場合、site が反映されるのは最悪の場合 1 時間強ぐらい後になります。

**Comment by saki7** [comment]
webhook 起動時に 前の webhook の PID で kill したりすることって可能ですか？

**Comment by melpon** [comment]
今のところそういう機能は無いですね。どこで kill されてもちゃんと動くようにすることを考えるのは面倒なのであまりやりたく無いところ…。

**Comment by melpon** [comment]
まあ今までも更新が何日も止まってることはあったので、まあ1時間ぐらい大丈夫だろう、という気持ちで行っていいかなと

**Comment by saki7** [comment]
おっけーです。ではminifyを頑張って殺すということで………
