### ISSUE TITLE
html の minify をやめる

### ISSUE THREAD

**Issue by saki7** [cpprefjp/site_generator#27]
from #26 

HTMLのminify処理自体が慣例としてもうあまり推奨されていないので、 minifyを丸ごと消すべきだと思います。何故推奨されなくなったかというと、いくつか理由があるのですが、

- 大体の Web サーバはデフォルトで gzip する
- CDN (github pages なども含む) に置く場合に html のサイズはほぼ無視できる
- スマホの普及とインターネット速度の底上げ
- HTML は minify すると文脈が壊れる
  - もともと HTML においては空白文字が意味を持っている
  - 例えば HTML のタグの間にスペースが１文字あるかないかで CSS の解釈が変わる

特に最後の理由が大きいです。基本的に HTML の空白文字の有無の仕様に依存するCSSを書くのはバッドノウハウではあるのですが、それを除いてもやはり minify はしない方が良いです。

サイドバーを抜き出す前にこれをやってしまうと流石にまずいので、サイドバーは動的にロードする必要あり (#28) 

再生成が４倍速になるという情報あり (#26)

**Comment by saki7** [comment]
blocks #46, #45

**Comment by saki7** [comment]
@melpon Sidebar v2 の実装は終わったので、html内の現行のサイドバーの埋め込みを丸ごと消してください。

**Comment by saki7** [comment]
消し方としては、 `<div class="tree">` は自身を含め全て消して良いです。その直上親要素の `<div class="col-sm-3 col-sm-pull-9">` が空になると思うので、中身が空の状態でそのまま残してください。

**Comment by saki7** [comment]
ああ、あと、minifyも消してください。僕の計算が正しければ、cpprefjp1ページあたりのファイルサイズが500KBから30KBくらいになるはずです。

**Comment by melpon** [comment]
了解です。

**Comment by melpon** [comment]
サイドバーの出力と minify をやめました https://github.com/cpprefjp/site_generator/commit/411bb3990113e5f88e3ba9b2ddeef6288ad0740f
サイドバー、スクロールが効かないのはこの変更のせいではないですよね…？

**Comment by saki7** [comment]
@melpon id=sidebarは、親要素に付けてください。子要素に新しくdivを掘ってしまうとそっちがサイドバーとして認識されてしまうので、正しくCSSが適用されません。（サイトバー＝ツリーではなく、サイドバーはツリーを包含）

説明不足でした。

**Comment by melpon** [comment]
あー、そう指定されてたことは分かってたんですが `base.html` 編集するのが面倒だったのでそうしてしまいました。スクロールが効かなくなるぐらい重要な要素とは思ってなかったので…。
修正しときます。

**Comment by saki7** [comment]
何が親要素で親要素が何を包含しているのか、小要素の数が幾つかという点はCSS3ではすごく重要です。

昔は「これは左、これは右」という書き方で済んでいたのですが、インターネットが複雑になるに連れて「この要素は子要素を均等に配分して、左右のスペースは右に集約する、余ったスペースは子要素に2:2:1で配分する、ただし最後の要素は自動拡張しない」というように、"意味"でフロントエンドを作る必要が出てきたのです。

という……蛇足でした。

**Comment by melpon** [comment]
修正ed https://github.com/cpprefjp/site_generator/commit/5ddbfc6163fabc18b29acf28f14dc8fa2a87c4f5

**Comment by saki7** [comment]
ありがとうございます。本番直ってました。

補足ですが、僕の上記の説明を厳密に適用した場合、バックエンドのフローとしては disable_sidebar ではなく disable_tree という扱いにした方が適切です。

この点は、いまは問題が起きていないのでノータッチで良いのですが、新たに最低限のナビゲーションを静的に埋め込む実装をする時には、確実に直す必要があります。 cpprefjp/kunai#16 

一応近い未来のためのメモということで。

対応ありがとうございました。基本的にバックエンドに由来した問題は起こらないはずなのですが、何か問題が起きたら教えて下さい。
