### ISSUE TITLE
サイドバーをメタ情報として抜き出す

### ISSUE THREAD

**Issue by saki7** [cpprefjp/site_generator#28]
ファイルの仕様については特に深く考えず json で良いと思う （階層構造を表現できていればどんな形式でもいい）

json を XHR で読みに行って動的に生成するフロントエンド側は１５分くらいあれば書けるので、問題はバックエンド

**Comment by saki7** [comment]
refs #26

**Comment by saki7** [comment]
せっかく crsearch で綺麗な json を吐いているので、site_generator の crsearch.json 生成処理で 

- 現段階で省かれているページを Index オブジェクトとして追加。 `type` は `"meta"`
- Namespace オブジェクトに サイドバー上の名前を表す `name` 属性を追加
- crsearch.js のクイックジャンプの検索結果で除外して欲しい Index にだけ `"nojump": true` を追加

この仕様変更でいけそう

**Comment by saki7** [comment]
現行のhtmlについている active が消えるという問題があるけど、 js 側で breadcrumb を見に行って頑張ればどうにかなりそう

**Comment by saki7** [comment]
boostjpでまだcrsearch.jsonを吐いていないのを忘れてた……

とりあえず cpprefjp の時だけ true になるフラグを立てますかね……

**Comment by melpon** [comment]
crsearch とサイドバーは全く別の機能なので、混ぜるよりも別々に置いた方が綺麗そうではありますね。容量的にはダメかもしれないですけど。

**Comment by saki7** [comment]
そうなんですよね。容量の問題があるのでとりあえず一本化した方がいいかなと。

**Comment by melpon** [comment]
boostjp の場合はサイドバーを静的に出力して、cpprefjp はサイドバーを出力せず動的に組み立てるようにする感じですかね？

**Comment by saki7** [comment]
はい。boostjpのメタ情報を正しく吐くようにするのはやり始めると手間がかかるので、まずcpprefjpだけ動的に作ってみたいと思います。 boostjp / cpprefjp かどうかのフラグはフロントエンドでも持てるので、 `<body>` に `class="boostjp"` と追加していただけると

**Comment by melpon** [comment]
了解です。

あとメタ情報ですが、

> 現段階で省かれているページを Index オブジェクトとして追加。 type は "meta"
> Namespace オブジェクトに サイドバー上の名前を表す name 属性を追加
> crsearch.js のクイックジャンプの検索結果で除外して欲しい Index にだけ "nojump": true を追加

[並び順のルール](https://github.com/cpprefjp/site_generator/blob/93fb8ca120c5b882d8f080123f77c6953c531658/settings/cpprefjp.py#L74-L135) があるので、順序の情報が必要そうです。 `get_order_priority` 関数が返す値だけ入れておけば何とかなりますかね？

**Comment by saki7** [comment]
それでお願いします。なんとかします。

**Comment by saki7** [comment]
と思ったのですが、 `page_id` があるので 並び順は一切入れなくてもこちらで対応できると思います。 `ORDER_PRIORITY_LIST` にハードコードされているものを 生 json の配列か何かに抜き出した上で、 cpprefjp/meta のようなまっさらなリポジトリの中に置いておいて頂ければ、フロントエンド側でそれだけ submodule で取りに行けます。

**Comment by melpon** [comment]
確かにフロントエンドと site_generator が共有して使う設定を置いたリポジトリはあっても良いかもしれないですね。

**Comment by melpon** [comment]
とりあえず以下の２つを実装しました https://github.com/cpprefjp/site_generator/commit/fdcef2b5f99f59a8142ee55a44b3af1328b30a0d 。

> 現段階で省かれているページを Index オブジェクトとして追加。 type は "meta"
> crsearch.js のクイックジャンプの検索結果で除外して欲しい Index にだけ "nojump": true を追加

`feature/sidebar` ブランチをチェックアウトして、`./crsearch.json/docker.sh run` を実行すれば新しい形式の `crsearch.json` が出てくると思います。

> Namespace オブジェクトに サイドバー上の名前を表す name 属性を追加

これは何を追加すればいいでしょうか？ `cpp11[meta cpp]` とかのメタ情報？

**Comment by saki7** [comment]
>> Namespace オブジェクトに サイドバー上の名前を表す name 属性を追加

> これは何を追加すればいいでしょうか？ cpp11[meta cpp] とかのメタ情報？

今のツリーのトップレベルの要素に表示されている名前です。

```
処理系
コンパイラの実装状況
メーリングリスト
外部ライブラリ
スタイル
article
editors_doc
言語機能
リファレンス
```

このうち、上５つについては元々crsearchで扱いが無かったものだと思います。これは、同名の Index （type: article なもの）を作って、それだけを含む同名のNamespaceを追加すれば良いのではないかなと。

**Comment by saki7** [comment]
__CRSearch__ オブジェクトに追加

```js
{
  "ids": [
    {
      "key" : ["コンパイラの実装状況"], // これが 12340001 相当
      "type": "meta"
    }
  ]
}
```

今まで省かれていたサイドバー上の要素について新しい __Namespace__ オブジェクトを追加

```json
{
  "indexes": [
    {
      "id": 12340001, // このIDは適当
      "page_id": [
        "",
      ]
    },
  ],
  "namespace": [
    "implementation-status"
  ],
  "path_prefixes": [
  "article"
  ]
},
```

というものを想像しています（もしかするとこれだと仕様的に欠陥があるかもしれない）

**Comment by saki7** [comment]
meta な物は IndexID::key で名前を指定すれば良いのですが、サイドバーのツリーのトップレベルの要素の名前に相当する概念がcrsearch.jsonの仕様上今まで無かったのです。なので、専用のNamespaceを掘って、
 `Namespace::name` を新設すれば良いのではないかなと。

**Comment by melpon** [comment]
あーなるほど、今だと `"namespace"` を空にして、`"page_id"` にファイル名を入れるようにしてます。こんな感じです。

```json
{
  "indexes": [
    {
      "id": 12340001, // このIDは適当
      "page_id": [
        "implementation-status",
      ],
      "nojump": true
    },
  ],
  "namespace": [],
  "path_prefixes": []
},
```

こうじゃなくて、特定の `"namespace"` で作ってしまえばいいってことですね。

**Comment by saki7** [comment]
@melpon なるほど。これだとやはり僕の上記コメントのように入れ子になった時につらい思いをしそうなので、僕が書いたような構造の方が良いのかなと（あれで欠陥が無ければ、ですが……）

**Comment by saki7** [comment]
上のjsonの例で肝心のnameを書き忘れていたので書いておきました……

**Comment by melpon** [comment]
対応しました（たぶん）。 https://github.com/cpprefjp/site_generator/commit/41a34cc03e8c7a63578709ed35ba552fcd876ca8

**Comment by saki7** [comment]
ありがとうございます！フロントエンドのブランチになるはやでとりこみます。

**Comment by melpon** [comment]
今デイリーで全 html に更新を掛けている理由は、追加したページの情報を全ページに反映させるためなので、もしこれが出来るようになったらデイリーで全 html を更新する必要も無くなりますね。

**Comment by faithandbrave** [comment]
グローバル修飾リストの適用は、全変換じゃないといけなそうな気がします。

**Comment by melpon** [comment]
site_generator を更新すると全変換走るようにしたので、サイドバーを抜き出すことで十分に変換が早くなってればそれで問題ないはず…！

**Comment by melpon** [comment]
と思ったけど `GLOBAL_QUALIFY_LIST.txt` は site 側にあった…。
まあほんとに変換が十分早くなってれば、site の更新でも全変換すればいいですしですし

**Comment by saki7** [comment]
@melpon 実装をお願いしておきながら大変申し訳無いのですが、 cpprefjp/kunai_config#1 に統合した方が良さそうという理由から `Namespace::name` は向こうに移動しました。現行のsite_generatorの対応箇所は僕が直しておきます。

**Comment by saki7** [comment]
nojump はcrsearch.jsonの範囲なので、めっちゃ助かってます。

**Comment by saki7** [comment]
仕様書を更新 https://github.com/cpprefjp/crsearch/wiki/crsearch.json%E3%83%95%E3%82%A9%E3%83%BC%E3%83%9E%E3%83%83%E3%83%88

**Comment by saki7** [comment]
「サイドバーをメタ情報として抜き出す」ために必要な site_generator の変更は、全て完了しました :tada: 

このIssueはcloseします。今後の実装は kunai の実装になります

**Comment by saki7** [comment]
Feature complete in tag v2.x.x
