### ISSUE TITLE
kunaiのpushで再生成が走る

### ISSUE THREAD

**Issue by saki7** [cpprefjp/site_generator#31]
@melpon 40分前のv1.0.1が反映されてないので、おそらく……

（static 以下だけ更新されればOK）

**Comment by saki7** [comment]
これ、1時間くらい時間がかかっているだけで、反映されてますね。

#26 で少し話に上がりましたが、もしかして kunai を push しても site_generator のディープな再生成が走るような仕様になってます？

**Comment by melpon** [comment]
はい、今は全ファイルを変換してます。ので直しておきます。

**Comment by saki7** [comment]
:joy: :joy: :joy: :ok_hand: :ok_man:  melpon/ghwebhook@72a58770f61f287f40c51f0af0a854b2f44a161c
