### ISSUE TITLE
site_generatorとkunaiをpingするためのdesignチームが欲しい

### ISSUE THREAD

**Issue by saki7** [cpprefjp/site_generator#33]
今だと cpprefjp/site で記事本体以外の問題が起きた時に誘導するのが少し大変です。 cpprefjp に design チームを作ればメンションしやすくなると思います

**Comment by faithandbrave** [comment]
いいと思います。
メンバーは誰がいればいいでしょう。

**Comment by saki7** [comment]
@saki7 @melpon @faithandbrave が良いと思います。この3人は今まで site_generator を頻繁に更新しています。

**Comment by faithandbrave** [comment]
では、 @melpon に確認がとれればそれで。
designは管理者である必要はないので、フロントエンド周りで継続的に貢献される方がいれば追加していきましょう。

**Comment by melpon** [comment]
ok です。

**Comment by saki7** [comment]
できた @cpprefjp/design
