### ISSUE TITLE
サイト全体のメタ情報を別リポジトリに分割して共有

### ISSUE THREAD

**Issue by saki7** [cpprefjp/site_generator#35]
@cpprefjp/coreteam 

https://github.com/cpprefjp/site_generator/issues/28#issuecomment-340751071

↑これが必要なので cpprefjp 上のリポジトリ作成の権限が欲しいです

**Comment by saki7** [comment]
今だと既存の管理権限はあるのですが新規作成権限が無いという感じです

**Comment by melpon** [comment]
多分付けれたと思います

**Comment by saki7** [comment]
まだ新規作成できないです。

**Comment by melpon** [comment]
ぐぬぬ…ほんとだ、Memberになってますね…

**Comment by melpon** [comment]
今度こそいけると思います！

**Comment by saki7** [comment]
お、できてました。あざす！ [cpprefjp/kunai_config](https://github.com/cpprefjp/kunai_config)
