### ISSUE TITLE
サンプルコード拡張記法をもとにJSONを生成してhtmlに埋め込む

### ISSUE THREAD

**Issue by saki7** [cpprefjp/site_generator#48]
https://github.com/cpprefjp/site_generator/issues/30#issuecomment-341321649

@melpon 暇な時にお願いします

**Comment by saki7** [comment]
ref: cpprefjp/site#473

**Comment by saki7** [comment]
Sidebar v2 のプロジェクトを一旦たたむまで僕は実質フロントエンドに手が出せないので、少なくともそれが終わるまでは何もしなくて大丈夫です

**Comment by melpon** [comment]
あー、最近流れる数が多くて完全に忘れてました。やっときます。

**Comment by saki7** [comment]
Issueのassign機能でassignされてないものは基本的に担当でないという認識でOKです。僕も久々にassignしたくらいなのでここ数日の大量のIssueは僕以外の担当者は居ないはずです。

あ、これも予定が立たないとかで厳しそうであればassign自分で外しちゃってOKなので外してください。

**Comment by melpon** [comment]
りょーかいです

**Comment by melpon** [comment]
[feature/kunai-info](https://github.com/cpprefjp/site_generator/tree/feature/kunai-mdinfo) ブランチに実装しました。
https://github.com/cpprefjp/site_generator/issues/30#issuecomment-341313373 に書いた通りの情報を入れています。何か問題があれば教えて下さい。

**Comment by saki7** [comment]
実装ありがとうございます、冬コミが終わったらこちらでも対応します

**Comment by melpon** [comment]
kunai の対応( https://github.com/cpprefjp/kunai/commit/582a94dc34b673c8ac3b750f6dbed7562190e113 )もできたので Close
