### ISSUE TITLE
最終更新ユーザーの、GitHubアカウントページへのリンクがほしい

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site_generator#5]
ページ右上に、以下のような表示が入りました。

```
最終更新日時: 2015年01月19日 14時20分13秒
Akira Takahashi が更新
```

このAkira Takahashiのところに、 <https://github.com/faithandbrave> へのリンクがほしいです。

**Comment by melpon** [comment]
そこはGitのコミットログを見てるのですが、コミット時のユーザ名とメールアドレスのみしか取れないので、GitHubへの関連付けはできません。
やるならユーザ名かメールアドレスからGitHubアカウントを割り出す辞書とか必要そうです。

**Comment by faithandbrave** [comment]
あぁ、なるほど。それでは今後、GitHubから何か情報をとる必要がでてきたら、ついでにお願いします。
