### ISSUE TITLE
コードブロック中のキーワードが自動リンクされなくなった

### ISSUE THREAD

**Issue by saki7** [cpprefjp/site_generator#51]
多分これ cpprefjp/markdown_to_html@4e9f3812b046ebd26d7cd7712a5dbe79b0a354c8 のregressionだと思うのですが、直接の原因がわからず………

**Comment by melpon** [comment]
おうふ…直しときます

**Comment by saki7** [comment]
直ってるの確認しました、対応ありがとうございます
