### ISSUE TITLE
注釈を貼れる記法の追加

### ISSUE THREAD

**Issue by yumetodo** [cpprefjp/site_generator#52]
cpprefjp/markdown_to_htmlの範疇になりそうだが、 https://github.com/cpprefjp/site/issues/485 を書いていてQiitaにはある注釈を貼る機能がほしいと思った。

[Markdown記法 チートシート - Qiita#注釈](https://qiita.com/Qiita/items/c686397e4a0f4f11683d#%E6%B3%A8%E9%87%88)

**Comment by saki7** [comment]
これってCommonMarkのページ内リンクで書く方法ありませんでしたっけ

**Comment by yumetodo** [comment]
ざっと探した感じ`<a name=foo></a>`したところに`[](#foo)`で飛ぶやつしか見当たりませんが、どういうやつのことでしょう？

**Comment by saki7** [comment]
## 見出しほげほげ

ああああああ　[要出典]

## 見出しほげ１

これは見出しほげ１です [^1]

[要出典]:https://cpprefjp.github.io/
[^1]:https://cpprefjp.github.io/reference/vector/emplace_back.html

---

```md
## 見出しほげほげ

ああああああ　[要出典]

## 見出しほげ１

これは見出しほげ１です [^1]

[要出典]:https://cpprefjp.github.io/
[^1]:https://cpprefjp.github.io/reference/vector/emplace_back.html
```

---

↑じゃダメですか？

**Comment by saki7** [comment]
8dff49e4a6d51404c03ebcaf4541f9ee95376968 これで注釈張ったので、これでよければcloseしていただけると。

**Comment by saki7** [comment]
あ、入れ子にするとうまく張れない。GitHubのプレビューだと張れてるのでこれはsite_generatorの問題かもしれない。

**Comment by saki7** [comment]
@melpon 今の https://github.com/cpprefjp/site/blob/055cb5f7cd1835883c6682aaa4489247fa7f707d/implementation.md のGitHub上のプレビューで表示されているのとまったく同じように本番でもリンクを張りたいのですが、本番でこれがうまく処理できていない原因とかに心当たりあったりしませんか……？

**Comment by yumetodo** [comment]
>↑じゃダメですか？

それだと注釈に文章書けないような・・・

**Comment by melpon** [comment]
@saki7 今変換で使っている Markdown ライブラリは CommonMark ではないので…。
Markdown ライブラリの[標準の Extension](https://pythonhosted.org/Markdown/extensions/index.html) を見てみましたが、うまくやれそうな機能は特に無いみたいですねぇ…。

**Comment by yumetodo** [comment]
>それだと注釈に文章書けないような・・・

ああ、結局`a`タグ使うと。それだと注釈で飛んだあと戻ってくるのを書くのが大変ではないかなと。

**Comment by melpon** [comment]
@yumetodo 自前で Markdown ライブラリの Extension を書くことになると思います。
ただ、CommonMark でない拡張に後々足を引っ張られそうな予感もあり、どうしようかなぁという感じですね。

**Comment by saki7** [comment]
@melpon ああ、なるほど。把握しました。

ちなみに、本件で直接の問題になっているのは、

```
[[^1]]
```

という入れ子のリンクにmarkdown_to_htmlのMarkdownパーサが対応してないということだと思います。

バックエンドのMarkdownパーサをCommonMark準拠のものに移行する場合は、Markdownの構文木に応じてcpprefjp拡張を適用している現行の処理を新しいパーサ向けに書き直せばよいので、基本的には難しくないと思います。作業量の問題だと思うので、余裕がある方がいればお願いしたいところです。

バックエンドのMarkdownライブラリを変更する場合は、 @melpon に意見を聞いてください。Pythonの流儀的にモダンであること、規格への準拠度が高いこと、構文木に応じた拡張が導入しやすいことなどが採用の条件です。

**Comment by saki7** [comment]
このIssueの本題の、「注釈を貼れる記法の追加」という点に関してですが、そういうものはCommonMarkには無さそうです。注釈記法をcpprefjpの拡張記法として導入することにはあまりメリットが見いだせないので、これはcloseします。

HTMLタグが直接書けるのはMarkdownの利点でもあるので、ここは `<a name="#cite-12345"></a>` の書き方で良いでしょう。色々なオープンソースソフトウェアのREADME.mdを見ていても、アンカーは大体そのようにして書かれていると思います。

**Comment by faithandbrave** [comment]
3,000ページを超えていて、ここだけのために新記法を導入するのは、コストが高いですね。なので、少なくとも今回は対応なしでよいと思います。

**Comment by saki7** [comment]
@yumetodo:

> それだと注釈に文章書けないような・・・

> ああ、結局aタグ使うと。それだと注釈で飛んだあと戻ってくるのを書くのが大変ではないかなと。

 上記2点について見解を書くのを忘れてました。まず前者は、僕が一連のコミットで書いたような書き方で書くのが良いと思います。後者は、wikiでよくあるような `[^1]` に対応する `[↑]` リンクのことを指しているのだと思いますが、これのために新記法を導入するのはコストが高いので、ひとまず対応無しで良いのではないかと思います。

**Comment by yumetodo** [comment]
了解しました。
