### ISSUE TITLE
Python 3 に移行する

### ISSUE THREAD

**Issue by melpon** [cpprefjp/site_generator#54]
crsearch 用 JSON 生成ツールが既に Python 3 なので合わせたい。
あと、今後 CircleCI あたりを使ったりしたいので、実行環境を一致させておきたいというのもある。

ヤバそうな点は、

- 各種ライブラリを Python 3 に対応したバージョンまで上げる必要があるので、ちゃんと動くかどうか分からない。特に Markdown ライブラリの拡張周り。
- 動いたとして、数が多いので既存の表示が壊れてるかどうかをチェックするのが難しい。新しいバージョンでも同じような HTML が生成されてくれれば、diff で軽く見るだけで済むので、そうだといいなぁという感じ。

**Comment by saki7** [comment]
@melpon jinja2から別のものに移行する予定ってありますか？

**Comment by melpon** [comment]
@saki7 PyPI 見る限りJinja2 は Python 3 に対応してるから必要無いかなと思ってます。
何か移行したい理由があったりします？

**Comment by saki7** [comment]
@melpon いえ、個人的には無いです。一応聞きたかっただけでした。

> 動いたとして、数が多いので既存の表示が壊れてるかどうかをチェックするのが難しい。新しいバージョンでも同じような HTML が生成されてくれれば、diff で軽く見るだけで済むので、そうだといいなぁという感じ。

これで思い出したんですが、サイドバーを実装した時に [GitHub pages の repo](https://github.com/cpprefjp/cpprefjp.github.io) で80万行くらいのdiffが生成されてたと思います。これのせいで git リポジトリが重くなってる気がするので、 `git gc` したいのですが、 GitHubで `git gc` する方法ってありましたっけ。

**Comment by melpon** [comment]
`git gc` って、HEAD から辿れるコミットは圧縮する程度だったと思うので、あまり効果が無さそうな気が…。

一度リポジトリを消して作り直してもいいかもしれませんね。
このリポジトリは自動生成したファイルをコミットする用途でしか使って無かったと思うので、消しても問題ないはず……たぶん。

**Comment by saki7** [comment]
@melpon なるほど。 `git gc --aggressive` みたいなのもあるんですが、これがきちんとGitHubに反映されるのかどうか僕はちょっと自信がないんですよね。なので、もし経験があれば教えてもらいたいなと思って聞いたのでした。

むかし個人のリポジトリで、パスワードを間違えてpushした時にGitHubサポートに連絡したら手厚い対応をしてくれたので、もしかしたら git gc 周りでもサポートが助けてくれるかもしれません。GitHubはオープンソースコミュニティには優しいので。

---

あとPython3関係で1つ聞きたいことが。

https://github.com/cpprefjp/site_generator/commit/edc7db805da0077321a6a87d422a170bac4606b6 でよく分からないままリスト内包表記と `itertools` を使ってしまったのですが、これはPython3の流儀的にはOKなんですかね？　特にリスト内包表記をどれくらい使い込んで良いのかという点が知りたいです。

**Comment by melpon** [comment]
> なので、もし経験があれば教えてもらいたいなと思って聞いたのでした。

なるほど。GitHub 上でそういうのをやった経験が無いので、ちょっと分からないです。

> これはPython3の流儀的にはOKなんですかね？

問題ないと思います。
自分だったら `itertools` 使うのをめんどくさがって `[file for d in _KNOWN_DIRS for file in get_files(d)]` と書きますが、好みレベルですね。

**Comment by saki7** [comment]
確かに一度リポジトリごとまっさらにした方が一瞬で綺麗になるので、そちらの方が良いかもしれません。どうしても履歴は残したいとかであれば、1つの方法としては `git gc` が良いかもしれないです。

大型アプデの後に表示が壊れているかをチェックするためには、やっぱり最終的には人間だと思うので、ここは協力したいです。そのときに git clone で 1GB のリポジトリが落ちてくるとなるとやりづらいので、このタイミングで直したいなーとちょっと思います。

---

Python3 周りは把握しました。ありがとうございます。（2段階リスト内包表記するのは盲点でした……）
