### ISSUE TITLE
README.md の手順を実行しても cpprefjp/site_generator の docker imageが作れない

### ISSUE THREAD

**Issue by forno** [cpprefjp/site_generator#56]
# 問題の提起
現在のREADME.md では cpprefjp を生成するための手順を準備と実行に分けています。
そのうちの準備を終わらせた段階でのdocker image list の結果がこちらです。

```bash
$ docker images 
REPOSITORY                         TAG                 IMAGE ID            CREATED             SIZE
cpprefjp/site_generator-crsearch   latest              2aab71612337        25 hours ago        91.5MB
hello-world                        latest              f2a91732366c        3 weeks ago         1.85kB
kunai                              0.0.0-alpine        a14f7741c56a        6 weeks ago         67.7MB
node                               8.9.0-alpine        a14f7741c56a        6 weeks ago         67.7MB
python                             3.6.2-alpine3.6     1b1ac8f23f73        3 months ago        86.1MB
```

`cpprefjp/site_generator` は実行手順の ./docker.sh 内で要求されていますが、生成されていないためエラーが生じます。

# 問題の原因分析
この問題は恐らく次のどちらかの要因によって起きていると考えられます。

## README.md の記述不足

README.md 内には `./docker.sh build` という記述がありません。
実行することにより、  `cpprefjp/size_generator` が生成されるようです。
すなわち、準備内に `./docker.sh build` の記述が必要なのではないでしょうか。

## 実行ファイル名の間違い

`./docker.sh` ではなく、別のパスにある `docker.sh` を用いるのが正解なパターン。
`./crsearch.json/docker.sh` とか?

# 要望
正しい実行手順がわかるようにしてほしい。

# 実行環境
OS: Ubuntu 16.04 server (Gnome desktop をインストールして使用)
Docker: Docker version 17.12.0-ce-rc3, build 80c8033

**Comment by melpon** [comment]
> README.md の記述不足

これのせいだと思います。
`./docker.sh build` したら問題なく動きましたか？

**Comment by forno** [comment]
試し終わりました。

ひとまずwebサーバまでは正常に動作したようです。 

localhost:8000 にアクセスすると何やらkunaiのCSSやjsが生成されてないっぽいですが、今回の件とは別件だと思うので問題があればまたIssue立てます。

余談ですが、家の回線が 1 Mbpsなのでダウンロードggg...ってことで先にIssue立てちゃいました。

**Comment by melpon** [comment]
CSS や JS も、「# kunai 用のデータを生成する」以下の場所でデータを生成してシンボリックリンクを張ってるのでちゃんと動くはずなのですが…。
ひとまず `./docker.sh build` を追加したのをコミットしておきます。

**Comment by forno** [comment]
再度実行手順を踏んでみたらkunai関係のファイルも生成されました。
なんでやろか・・・。

というわけで、 `./docker.sh build` が必要ということで合っているみたいです。

**Comment by melpon** [comment]
了解です。確認ありがとうございます！

**Comment by melpon** [comment]
手順を追加したので Close します
