### ISSUE TITLE
並び替えルールに `op_compare_3way` を追加する

### ISSUE THREAD

**Issue by usagi** [cpprefjp/site_generator#67]
経緯: https://github.com/cpprefjp/site/issues/596

**Comment by usagi** [comment]
入れる場所は比較演算子の最後がいいかな。

![image](https://user-images.githubusercontent.com/115972/56082729-18a2d100-5e57-11e9-9935-2f729c544dd3.png)

**Comment by faithandbrave** [comment]
これで完了です。対応ありがとうございました。
