### ISSUE TITLE
cpprefjpのURL末尾に#gsc.tab=0がつく

### ISSUE THREAD

**Issue by yumetodo** [cpprefjp/site_generator#70]
おそらくGoogle のカスタム検索の設定に問題があると思います

ref:

- [Google のカスタム検索エンジンは便利だけど、設置すると URL の末尾に「#gsc.tab=0」がつくのを修正したい | t011.org](https://t011.org/internet/96733.html)

**Comment by faithandbrave** [comment]
@melpon カスタム検索エンジンの設定みれますか？

**Comment by melpon** [comment]
これが付くと何か問題が起きるんです？

**Comment by melpon** [comment]
多分これかな ![image](https://user-images.githubusercontent.com/816539/84730567-70941500-afd1-11ea-9258-f21f0cdc91ff.png)

**Comment by yumetodo** [comment]
URLコピーするときにめんどくさいです。長くなって。

**Comment by melpon** [comment]
別に付いたままでもいいとは思いますけど、変えるのはすぐ出来そうですね。
ただこれで何かの機能が使えなくなると思うんですけど、どんな機能か分かる人います？

**Comment by faithandbrave** [comment]
https://support.google.com/programmable-search/answer/3037004?hl=en
http://algorhythnn.jp/blg/2014/02/06/google_v2-site_search-search/

ブラウザの戻るボタンでまえの検索結果が表示されるよう保存しておくのだそうです。

**Comment by melpon** [comment]
戻る、普通に前の検索結果が表示されそうな気がするけどどうなんだろう…。とりあえず無効にしてみますか。不都合あるようだったらまた有効にしますね。

**Comment by melpon** [comment]
無効にしてみました。

**Comment by yumetodo** [comment]
無効にしても何が変わったのかわからないので無効のままでいいのではと思います。

**Comment by melpon** [comment]
問題無さそうなので閉じます。
