### ISSUE TITLE
見出し2と見出し3を判別できるようにしたい

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site_generator#8]
です。

たとえばnullptrのページですが、
<http://cpprefjp.github.io/lang/cpp11/nullptr.html>

「仕様」が見出し2で、「型の分類」「型変換」「比較演算」が見出し3です。いまだと、フォントサイズが1〜2ポイント違うだけのように見えて、ぱっと見で階層的な構成になっていることがわかりにくいです。
検討お願いしますー。

**Comment by usagi** [comment]
案: `content-body > h1:before` `content-body > h2:before` などに書籍でもよくあるような見出しレベルのわかるアイコン（またはそれっぽく見える文字＋色をやや淡目にして見出しを食わないように）を入れてあげると見たわかり易さと副作用として簡単ながらも意匠性も向上して良いかもしれない。

**Comment by melpon** [comment]
デザインよく分からないので、margin-left入れるだけでもいいかなぁ…

**Comment by faithandbrave** [comment]
見出しレベル2には、罫線(下線、Markdownでは「`***`」)を入れるとかすれば差別化できそう。

**Comment by faithandbrave** [comment]
参考になりそうなページ：
<http://coliss.com/articles/build-websites/operation/css/css-tutorial-heading-set-styling-by-codrops.html>

**Comment by usagi** [comment]
.md では `#` による見出し定義ではレベリング情報が欠損しないので、見出しのレベリングを記事内で行う場合には `#` を使う事にしたら何かと楽かな。

```md
# level-1
content-1
## level-2
content-1-2
### level-3
content-1-2-3
```

-----
実装担当にアサインしているmelponに対して私は提案のみなので、「よくわからないので」も一理ありで、とりあえずはわかりやすい簡単な解決方法で対応しつつ、より向上した実装のニーズには後日対応するチケットを出しておくというのでも、何れ現時点より都度漸近的によくなるのでそれも構わないのではないかなと思っています。あくまでも担当に強いご負担となりませんように。

**Comment by melpon** [comment]
こんな感じでいいですかね？
![2015-11-01 18 51 56](https://cloud.githubusercontent.com/assets/816539/10868200/bd314266-80c9-11e5-990f-e267d540f17e.png)

**Comment by usagi** [comment]
↑ :+1:

**Comment by faithandbrave** [comment]
ありがとうございます！サイト全体のアップデートをしておいてくださーい(自動アップデートされるならそれでOK)。
