### ISSUE TITLE
`markdown` パッケージがbacktickに対して `trim_start` のようなことをするので表示が崩れる問題

### ISSUE THREAD

**Issue by wx257osn2** [cpprefjp/site_generator#82]
[`std::ranges::subrange`](https://cpprefjp.github.io/reference/ranges/subrange.html)のページで，

```md
[`subrange_kind`](subrange_kind.md)` K`が
```

の表示が以下のようになっています．

![image](https://user-images.githubusercontent.com/1091761/201624149-4c512ed8-db44-43fa-9e64-2f3a84302cce.png)

軽く調べたところ，どうも[`markdown` パッケージ](https://github.com/Python-Markdown/markdown/)の挙動としてbacktick内の文字列に対して勝手に前後の空白を潰す処理をしているようです．
これを抑制するために `site` 側でZWSPを挿したら[CIでコケた](https://github.com/cpprefjp/site/actions/runs/3460078382/jobs/5776207042)ので(この手のチェックあるんすね…)，大人しく(正攻法ですし) `site_generator` 側でなんらかの対処をしたほうが良さそう

**Comment by faithandbrave** [comment]
あ、ひとまずcpprefjpルールとして、両端のスペースはバッククォート内に含めないこととしています。
それでもスペースはコードとして連結されます。

**Comment by faithandbrave** [comment]
```md
[`subrange_kind`](subrange_kind.md) `K`が
```

こう書いてもらえれば。

**Comment by faithandbrave** [comment]
アンドキュメントだったので書いておきます。
https://github.com/cpprefjp/site/blob/master/editors_doc/specialized.md

**Comment by faithandbrave** [comment]
書きました。
https://cpprefjp.github.io/editors_doc/specialized.html

**Comment by wx257osn2** [comment]
直しました．教示・追記ありがとうございます :bow: https://github.com/cpprefjp/site/commit/abd229030a4ada8cc21ffb7dfa06dae05ba45296
