### ISSUE TITLE
ParseError例外を捕捉しているところで、例外が投げられて落ちている

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/site_generator#9]
cpprefjp/siteでの、 @usagi さんの以下のコミットで発生している変換エラーですが、
<https://github.com/cpprefjp/site/commit/166dfcc282935f02dc6d85708e55463fe616f067>

以下の行でUnicodeError例外が発生しています。

```
File "/home/melpon/site_generator/markdown_to_html/html_attribute.py", line 281, in run
    print u'{0:5d} {1}'.format(n + 1, x)
```

該当行があるfor文の前あたりで、Markdownの行番号をprintしておいてほしいです。
ちなみに、variable_templates.mdの文字コードはUTF-8でした。そこは問題なさそうです。

**Comment by usagi** [comment]
むむ、気づきませんでマージしてしまいご面倒をお掛けします。
